# Trabajo integrador - Parte 1
## Python y Numpy

**Nombre**: Luis Pablo Segovia

In [2]:
import numpy as np

## Primer ejercicio

Dada una matriz en formato *numpy array*, donde cada fila de la matriz representa un vector matemático, se requiere computar las normas $l_0$, $l_1$, $l_2$, $l_{\infty}$, según la siguientes definiciones:

\begin{equation}
    ||\mathbf{x}||^{p} = \bigg(\sum_{j=1}^{n}{|x_i|^p}\bigg)^{\frac{1}{p}}
\end{equation}

con los casos especiales para $p=0$ y $p=\infty$ siendo:

\begin{equation}
    \begin{array}{rcl}
        ||\mathbf{x}||_0 & = & \bigg(\sum_{j=1 \wedge x_j != 0}{|x_i|}\bigg)\\
        ||\mathbf{x}||_{\infty} & = & \max_{i}{|x_i|}\\
    \end{array}
\end{equation}

In [3]:
# Para computar las normas usamos de referencia https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
A = np.arange(9).reshape((3,3)) # ejemplo de matriz para computar las normas

# l0_norm = np.linalg.norm(A, ord=0)
l1_norm = np.linalg.norm(A, ord=1)
l2_norm = np.linalg.norm(A, ord=2)
linf_norm = np.linalg.norm(A, ord=np.inf)

print("Matriz A: \n", A)

print("\nLa norma l1 es: ", l1_norm)
print("La norma l2 es: ", l2_norm)
print("La norma linf es: ", linf_norm)

Matriz A: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

La norma l1 es:  15.0
La norma l2 es:  14.226707390822694
La norma linf es:  21.0


## Segundo Ejercicio

En clasificación contamos con dos arreglos, la “verdad” y la “predicción”. Cada elemento de los arreglos pueden tomar dos valores, “True” (representado por 1) y “False” (representado por 0). Entonces podemos definir 4 variables:

* True Positive (TP): El valor verdadero es 1 y el valor predicho es 1
* True Negative (TN): El valor verdadero es 0 y el valor predicho es 0
* False Positive (FP): El valor verdadero es 0 y el valor predicho es 1
* False Negative (FN): El valor verdadero es 1 y el valor predicho es 0

A partir de esto definimos:

* Precision = TP / (TP + FP)
* Recall = TP / (TP + FN)
* Accuracy = (TP + TN) / (TP + TN + FP + FN)
 
Calcular las 3 métricas con Numpy y operaciones vectorizadas.

In [4]:
truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

In [5]:
# Definimos las 4 variables
TP = np.sum(np.where((truth == 1) & (prediction == 1), 1, 0))
TN = np.sum(np.where((truth == 0) & (prediction == 0), 1, 0))
FP = np.sum(np.where((truth == 0) & (prediction == 1), 1, 0))
FN = np.sum(np.where((truth == 1) & (prediction == 0), 1, 0))

# Calcular Precisión
precision = TP / (TP+FP)
print(f"La Precisión es: {precision*100}%")

# Calcular Recall
recall = TP / (TP+FN)
print(f"El Recall es: {recall*100}%")

# Calcular Accuracy
accuracy = (TP+TN) / (TP+TN+FP+FN)
print(f"El Accuracy es: {accuracy*100}%")

La Precisión es: 50.0%
El Recall es: 50.0%
El Accuracy es: 40.0%


## Tercer ejercicio

Crear una función que separe los datos en train-validation-test. Debe recibir de parametros:

- X: Array o Dataframe que contiene los datos de entrada del sistema.
- y: Array o Dataframe que contiene la(s) variable(s) target del problema.
- train_percentage: _float_ el porcentaje de training.
- test_percentage: _float_ el porcentaje de testing.
- val_percentage: _float_ el porcentaje de validación.
- shuffle: _bool_ determina si el split debe hacerse de manera random o no.

Hints: 

* Usar Indexing y slicing
* Usar np.random.[...]

In [100]:
def split(X_input,
          Y_input,
          train_size=0.7,
          val_size=0.15,
          test_size=0.15,
          random_state=42,
          shuffle=True):
    
    return NotImplementedError

def split_input(X, Y, 
                train_percentage=0.80, 
                test_percentage=0.10, 
                val_percentage=0.10, 
                shuffle=True):
      
    def _inner_split(array):

        arr_train_split = array[:int(train_percentage*len(array))]
        arr_val_split = array[int(train_percentage*len(array)):int((train_percentage+val_percentage)*len(array))]
        arr_test_split = array[int((train_percentage+val_percentage)*len(array)):]

        return arr_train_split, arr_val_split, arr_test_split
    
    X = np.array(X)
    Y = np.array(Y)

    if shuffle:
        train_percentage = np.random.random()
        val_percentage = train_percentage*np.random.random()
        test_percentage = 1.0 - train_percentage - val_percentage
    
    X_train, X_val, X_test = _inner_split(X)
    Y_train, Y_val, Y_test = _inner_split(Y)
    
    return X_train, X_val, X_test, Y_train, Y_val, Y_test